version: '3'

services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: bash -c "bundle && bundle exec rake db:create db:migrate db:seed && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
