version: '3'

services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: bash -c "bundle exec rails server -b  0.0.0.0"
    depends_on:
      - "mongodb"

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
